In [1]:
# numpy 배열 브로드캐스팅 기능
import numpy as np

In [7]:
# nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nums = np.arange(1, 10+1)
"""
    np.arange(10) : 0~9
    np.arange(1, 10+1) : 1~10
    np.arange(1, 10+1, 2) : 1, 3, 5, 7, 9
"""
nums += 10
nums *= 2
nums

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [ ]:
# 배열의 차원 변경, reshape (원본 데이터는 바뀌지 않는다)
nums2 = nums.reshape(2, 5)  # 2행 5열
nums2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [10]:
nums3 = nums.reshape(5, 2)  # 5행 2열
nums3

array([[22, 24],
       [26, 28],
       [30, 32],
       [34, 36],
       [38, 40]])

In [11]:
# 개수가 맞지 않으면? -> 오류 발생 ValueError
nums4 = nums.reshape(3, 3)
nums4

ValueError: cannot reshape array of size 10 into shape (3,3)

In [17]:
# nums5 = nums.reshape(10, 1)
nums5 = nums.reshape(-1, 1)  # 전체 열을 전체 행의 개수로
nums5

array([[22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38],
       [40]])

In [18]:
np.random.shuffle(nums)
nums

array([38, 34, 40, 28, 36, 26, 30, 24, 22, 32])

In [19]:
fruits = np.array(['사과', '오렌지', '바나나', '망고', '멜론'])
fruits[[1, 2, 3]]

array(['오렌지', '바나나', '망고'], dtype='<U3')

In [20]:
fruits[[False, True, False, True, False]]  # Boolean Indexing

array(['오렌지', '망고'], dtype='<U3')