In [4]:
from scipy.stats import randint, uniform

ri = randint(0, 10)  # 0~9 랜덤 숫자
ri.rvs(11)           # 0~9 랜덤 숫자 11개 생성

array([2, 1, 9, 8, 0, 9, 1, 0, 7, 1, 2])

In [5]:
import numpy as np

np.unique(ri.rvs(1000), return_counts=True)  # 중복된 개수 함께 반환

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([123, 107,  94, 102, 100,  84, 107,  82,  96, 105]))

In [6]:
ui = uniform(0, 1)  # 0~1 랜덤 실수
ui.rvs(5)           # 0~1 랜덤 실수 5개 생성

array([0.67009234, 0.10316376, 0.32198995, 0.06300531, 0.88566601])